### ISSUE TITLE
尝试在win10本地运行出错了

### ISSUE THREAD

**Issue by sovzzz** [MaxSecurity/BiliExper#15]
第一遍报错是缺个模块，装了模块又出现如下报错
`Traceback (most recent call last):
  File "D:\bili\biliexp.py", line 7, in <module>
    from BiliClient import asyncbili
  File "D:\bili\BiliClient\__init__.py", line 11, in <module>
    from .asyncBiliApi import asyncBiliApi as asyncbili #B站接口模块，由aiohttp模块实现异步http请求
  File "D:\bili\BiliClient\asyncBiliApi.py", line 9, in <module>
    from .wasm_enc import calc_sign
  File "D:\bili\BiliClient\wasm_enc\__init__.py", line 1, in <module>
    from .spyder import calc_sign
  File "D:\bili\BiliClient\wasm_enc\spyder.py", line 170, in <module>
    wasm = RustWasm(pathname, imports)
  File "D:\bili\BiliClient\wasm_enc\rustwasm.py", line 156, in __init__
    self.memory = exports['memory']
TypeError: 'method' object is not subscriptable`
但是根本找不到method在哪里。
实在很好奇原作者的bat文件到底是什么内容。

**Comment by acooler15** [comment]
有没有`pip install -r requirements.txt`?

**Comment by sovzzz** [comment]
> 有没有`pip install -r requirements.txt`?
除了severless framework都有

**Comment by sovzzz** [comment]
> 有没有`pip install -r requirements.txt`?

除了severless framework都有

**Comment by MaxSecurity** [comment]
> > 有没有`pip install -r requirements.txt`?
> 
> 除了severless framework都有

有可能是你python环境出现了问题 建议使用python3.8版本的python
