### ISSUE TITLE
应援团错误

### ISSUE THREAD

**Issue by insoxin** [MaxSecurity/BiliExper#16]
`Error: 7-27 06:50:39,801] [ERROR]: Task exception was never retrieved
35
future: <Task finished name='Task-6' coro=<group_sign_task() done, defined at /home/runner/work/BiliExper/BiliExper/tasks/group_sign_task.py:5> exception=TypeError('string indices must be integers')>
36
Traceback (most recent call last):
37
  File "/home/runner/work/BiliExper/BiliExper/tasks/group_sign_task.py", line 20, in group_sign_task
38
    sign = await biliapi.groupSign(group["group_id"], group["owner_uid"])
39
TypeError: string indices must be integers
40

41
During handling of the above exception, another exception occurred:
42

43
Traceback (most recent call last):
44
  File "/home/runner/work/BiliExper/BiliExper/tasks/group_sign_task.py", line 22, in group_sign_task
45
    logging.warning(f'{biliapi.name}: 给{group["group_name"]}应援异常，原因为{str(e)}')`

**Comment by acooler15** [comment]
tasks/group_sign_task.py文件第18行，将`    for group in ret["data"]:`改为`    for group in ret["data"]["list"]:`

**Comment by redy110** [comment]
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<run_user_tasks() done, defined at BiliExp.py:83> exception=IndentationError('unindent does not match any outer indentation level', ('/home/runner/work/BiliExper/BiliExper/tasks/group_sign_task.py', 18, 37, '   for group in ret["data"]["list"]:\n'))>
Traceback (most recent call last):
  File "BiliExp.py", line 109, in run_user_tasks
    task_module = import_module(f'tasks.{task}') #加载任务模块
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/work/BiliExper/BiliExper/tasks/group_sign_task.py", line 18
    for group in ret["data"]["list"]:
                                    ^
IndentationError: unindent does not match any outer indentation level

> tasks/group_sign_task.py文件第18行，将` for group in ret["data"]:`改为` for group in ret["data"]["list"]:`

**Comment by acooler15** [comment]
缩进出错了。。。

**Comment by acooler15** [comment]
``` python
from BiliClient import asyncbili
from .push_message_task import webhook
import logging

async def group_sign_task(biliapi: asyncbili) -> None:
    '''应援团签到'''
    try:
        ret = await biliapi.getMyGroups()
    except Exception as e:
        logging.warning(f'{biliapi.name}: 获取应援团信息异常，原因为{str(e)}，跳过应援团签到')
        return
    if ret["code"] != 0:
        logging.info(f'{biliapi.name}: 获取应援团信息失败，信息为:{ret["message"]}，跳过应援团签到')
        webhook.addMsg('msg_simple', f'{biliapi.name}:应援团签到失败\n')
        return

    su, er = 0, 0
    for group in ret["data"]["list"]:
        try:
            sign = await biliapi.groupSign(group["group_id"], group["owner_uid"])
        except Exception as e:
            logging.warning(f'{biliapi.name}: 给{group["group_name"]}应援异常，原因为{str(e)}')
            er += 1
        else:
            if sign["code"] == 0 and sign["data"]["status"] == 0:
                logging.info(f'{biliapi.name}: 给{group["group_name"]}应援成功')
                su += 1
            else:
                logging.info(f'{biliapi.name}: 给{group["group_name"]}应援失败，原因为:{sign["message"]}')
                er += 1
    if er > 0:
        webhook.addMsg('msg_simple', f'{biliapi.name}:应援团签到成功{su}个,失败{er}个\n')

```

**Comment by acooler15** [comment]
或者直接下载`https://raw.githubusercontent.com/MaxSecurity/BiliExper/2f95a4ad06aff1da387b9253995a43c6e72c25f5/tasks/group_sign_task.py`这个替换掉原文件

**Comment by acooler15** [comment]
@redy110 如果是git方式下载，用命令`git reset --hard HEAD^`回退到上个commit，也可以解决
